//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPosto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int codPedido { get; set; }
        public int codItemPedido { get; set; }
        public int codVendedor { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual ItemPedido ItemPedido { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
