//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPosto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public Produto()
        {
            this.ItemPedido = new HashSet<ItemPedido>();
        }
    
        public int codProduto { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string unidade { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<decimal> estoque { get; set; }
        public int codTipo { get; set; }
    
        public virtual ICollection<ItemPedido> ItemPedido { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
